### ISSUE TITLE
Got an error while trying to use the .dll, also a suggestion to improve how it is compiled.

### ISSUE THREAD

**Issue by Mario0051** [rikka0w0/ExplorerContextMenuTweaker#1]
I can compile the .dll successfully, though it was a bit of a struggle to compile, but it doesn't seem to work, it gives this error:
`
The module ".\ExplorerContextMenuTweaker.dll" was loaded but the call to DllRegisterServer failed with error code 0x80070005.
`
Also, for a suggestion, I think the code should be upgraded to the most recent version of Visual Studio, because I had to re-target the solution to the latest Windows 10 SDK and had to install the "Windows XP support for C++" with the Visual Studio Installer.

**Comment by rikka0w0** [comment]
code 0x80070005 is described as ACCESS DENIED, so try to launch a cmd window with administrative  privilege, then use regsvr32.exe (the 64-bit version) to register the dll, and it should work.

Check out the release page!

**Comment by Mario0051** [comment]
It did work. Thanks.
