### ISSUE TITLE
Where can you find "VC2017 x64 runtime"? I have the VC++2017 Redistributable but it still gives errors.

### ISSUE THREAD

**Issue by Mario0051** [rikka0w0/ExplorerContextMenuTweaker#2]
Where do I find the VC2017 x64 runtime? I have the Microsoft Visual C++ 2017 Redistributable installed on my computer but it gives me these errors: 
```
Unable to locate __PerformInjection() in ShellPayload.dll
Unable to locate __SetCurrentPIDL() in ShellPayload.dll
Unable to locate __SetContextMenuFlags() in ShellPayload.dll
```

**Comment by rikka0w0** [comment]
You can find them on this page:
https://support.microsoft.com/en-au/help/2977003/the-latest-supported-visual-c-downloads

You have to use a powershell window or a cmd window with administrative privilege to execute the "regsvr32" command

**Comment by Mario0051** [comment]
That works. Thanks.
