### ISSUE TITLE
batch file to install and register files ?

### ISSUE THREAD

**Issue by innuendo33** [rikka0w0/ExplorerContextMenuTweaker#4]
Hi rikka0w0

First gratz to provide such tool ! running well on 19H1 . 
I tried making a batch files to copy necessary files to system32 and register them but without success.
Could you help me show what command use in such bat file ( *.cmd ) to automate full process instead of manually? 

Best regards

**Comment by rikka0w0** [comment]
I guess you to need to run that bat file with administrative priviledge which is required to copy files to system folders

**Comment by innuendo33** [comment]
oh thanks for answer , I now understand what prevent batch file to work :/ 
Anyway your work is awesome and so happy to get back classic menus under W10 ! 
Keep the hard work ^^
