### ISSUE TITLE
部分文件（图标—）右键出现的菜单背景无更改，仍是默认样式

### ISSUE THREAD

**Issue by xigongyue** [rikka0w0/ExplorerContextMenuTweaker#8]

**Comment by rikka0w0** [comment]
这个方案暂时不准备继续开发了 没时间

考虑下这个方案代替？
https://gist.github.com/rikka0w0/971e247871154427d5e62c7b3a7ac1d4

**Comment by xigongyue** [comment]
感谢您如此快的回复，我会考虑的
